// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tripflow.Api.Data;

#nullable disable

namespace Tripflow.Api.Data.Migrations
{
    [DbContext(typeof(TripflowDbContext))]
    [Migration("20260111190448_AddUsersAndTourGuide")]
    partial class AddUsersAndTourGuide
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tripflow.Api.Data.Entities.CheckInEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CheckedInAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TourId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("TourId");

                    b.HasIndex("TourId", "ParticipantId")
                        .IsUnique();

                    b.ToTable("checkins", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.ParticipantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CheckInCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TourId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CheckInCode")
                        .IsUnique();

                    b.HasIndex("TourId");

                    b.ToTable("participants", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.TourEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("GuideUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("GuideUserId");

                    b.ToTable("tours", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.TourPortalEntity", b =>
                {
                    b.Property<Guid>("TourId")
                        .HasColumnType("uuid");

                    b.Property<string>("PortalJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TourId");

                    b.ToTable("tour_portals", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.ParticipantEntity", b =>
                {
                    b.HasOne("Tripflow.Api.Data.Entities.TourEntity", "Tour")
                        .WithMany("Participants")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.TourEntity", b =>
                {
                    b.HasOne("Tripflow.Api.Data.Entities.UserEntity", "GuideUser")
                        .WithMany("GuidedTours")
                        .HasForeignKey("GuideUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GuideUser");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.TourPortalEntity", b =>
                {
                    b.HasOne("Tripflow.Api.Data.Entities.TourEntity", "Tour")
                        .WithOne("Portal")
                        .HasForeignKey("Tripflow.Api.Data.Entities.TourPortalEntity", "TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.TourEntity", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("Portal");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("GuidedTours");
                });
#pragma warning restore 612, 618
        }
    }
}
