// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tripflow.Api.Data;

#nullable disable

namespace Tripflow.Api.Data.Migrations
{
    [DbContext(typeof(TripflowDbContext))]
    [Migration("20260422084921_AddTransferSeatCompartment")]
    partial class AddTransferSeatCompartment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Xml")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FriendlyName");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.ActivityMealGroupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowNote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("AllowOther")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("EventId");

                    b.HasIndex("OrganizationId", "ActivityId", "SortOrder");

                    b.HasIndex("OrganizationId", "EventId", "ActivityId");

                    b.ToTable("activity_meal_groups", null, t =>
                        {
                            t.HasCheckConstraint("CK_activity_meal_groups_sort_order", "\"SortOrder\" >= 1");
                        });
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.ActivityMealOptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("OrganizationId", "GroupId", "SortOrder");

                    b.ToTable("activity_meal_options", null, t =>
                        {
                            t.HasCheckConstraint("CK_activity_meal_options_sort_order", "\"SortOrder\" >= 1");
                        });
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.ActivityParticipantLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActorRole")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "ActivityId", "ParticipantId", "CreatedAt")
                        .IsDescending(false, false, false, true);

                    b.HasIndex("OrganizationId", "EventId", "ActivityId", "CreatedAt")
                        .IsDescending(false, false, false, true);

                    b.ToTable("activity_participant_logs", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.AuditLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ExtraJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Role")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TargetId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Action", "CreatedAt");

                    b.HasIndex("OrganizationId", "CreatedAt");

                    b.HasIndex("UserId", "CreatedAt");

                    b.HasIndex("TargetType", "TargetId", "CreatedAt");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.CheckInEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CheckedInAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("EventId", "ParticipantId")
                        .IsUnique();

                    b.ToTable("checkins", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.EventAccommodationSegmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DefaultAccommodationDocTabId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DefaultAccommodationDocTabId");

                    b.HasIndex("EventId");

                    b.HasIndex("OrganizationId", "EventId", "DefaultAccommodationDocTabId");

                    b.HasIndex("OrganizationId", "EventId", "StartDate", "SortOrder");

                    b.ToTable("event_accommodation_segments", null, t =>
                        {
                            t.HasCheckConstraint("CK_event_accommodation_segments_date_range", "\"EndDate\" >= \"StartDate\"");
                        });
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.EventActivityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("CheckInEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("CheckInMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("EntryOnly");

                    b.Property<string>("Directions")
                        .HasMaxLength(15000)
                        .HasColumnType("character varying(15000)");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("EventDayId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("LocationName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MenuText")
                        .HasMaxLength(15000)
                        .HasColumnType("character varying(15000)");

                    b.Property<string>("Notes")
                        .HasMaxLength(15000)
                        .HasColumnType("character varying(15000)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProgramContent")
                        .HasMaxLength(15000)
                        .HasColumnType("character varying(15000)");

                    b.Property<bool>("RequiresCheckIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("SurveyUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("EventDayId");

                    b.HasIndex("EventId");

                    b.HasIndex("OrganizationId", "EventId");

                    b.HasIndex("OrganizationId", "EventDayId", "StartTime");

                    b.ToTable("event_activities", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.EventDayEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Notes")
                        .HasMaxLength(15000)
                        .HasColumnType("character varying(15000)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlacesToVisit")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("OrganizationId", "EventId", "Date");

                    b.HasIndex("OrganizationId", "EventId", "SortOrder");

                    b.ToTable("event_days", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.EventDocTabEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("OrganizationId", "EventId", "SortOrder");

                    b.ToTable("event_doc_tabs", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.EventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmergencyPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("EventAccessCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("GuideName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GuidePhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LeaderName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LeaderPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("WhatsappGroupUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("EventAccessCode")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "StartDate");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.EventGuideEntity", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GuideUserId")
                        .HasColumnType("uuid");

                    b.HasKey("EventId", "GuideUserId");

                    b.HasIndex("EventId");

                    b.HasIndex("GuideUserId");

                    b.ToTable("event_guides", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.EventItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("OrganizationId", "EventId", "Name")
                        .IsUnique();

                    b.ToTable("event_items", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.EventParticipantLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorRole")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Result")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Success");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EventId", "CreatedAt")
                        .IsDescending(false, false, true);

                    b.HasIndex("OrganizationId", "ParticipantId", "CreatedAt")
                        .IsDescending(false, false, true);

                    b.HasIndex("OrganizationId", "EventId", "ParticipantId", "CreatedAt")
                        .IsDescending(false, false, false, true);

                    b.ToTable("event_participant_logs", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.EventPortalEntity", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PortalJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("event_portals", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.OrganizationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.OrganizationGuideEntity", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GuideUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("OrganizationId", "GuideUserId");

                    b.HasIndex("GuideUserId");

                    b.ToTable("organization_guides", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.ParticipantAccommodationAssignmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BoardType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OverrideAccommodationDocTabId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<string>("PersonNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RoomNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RoomType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("SegmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OverrideAccommodationDocTabId");

                    b.HasIndex("SegmentId");

                    b.HasIndex("ParticipantId", "SegmentId")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "EventId", "SegmentId");

                    b.ToTable("participant_accommodation_assignments", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.ParticipantActivityWillNotAttendEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("WillNotAttend")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("ParticipantId", "ActivityId")
                        .IsUnique();

                    b.ToTable("participant_activity_will_not_attend", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.ParticipantDetailsEntity", b =>
                {
                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccommodationDocTabId")
                        .HasColumnType("uuid");

                    b.Property<string>("AgencyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ArrivalAirline")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ArrivalArrivalAirport")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<TimeOnly?>("ArrivalArrivalTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("ArrivalBaggageAllowance")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ArrivalBaggagePieces")
                        .HasColumnType("integer");

                    b.Property<int?>("ArrivalBaggageTotalKg")
                        .HasColumnType("integer");

                    b.Property<string>("ArrivalCabinBaggage")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ArrivalDepartureAirport")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<TimeOnly?>("ArrivalDepartureTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("ArrivalFlightCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly?>("ArrivalFlightDate")
                        .HasColumnType("date");

                    b.Property<string>("ArrivalPnr")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ArrivalTicketNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ArrivalTransferCompartmentNo")
                        .HasColumnType("text");

                    b.Property<string>("ArrivalTransferDriverInfo")
                        .HasColumnType("text");

                    b.Property<string>("ArrivalTransferDropoffPlace")
                        .HasColumnType("text");

                    b.Property<string>("ArrivalTransferNote")
                        .HasColumnType("text");

                    b.Property<string>("ArrivalTransferPickupPlace")
                        .HasColumnType("text");

                    b.Property<TimeOnly?>("ArrivalTransferPickupTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("ArrivalTransferPlate")
                        .HasColumnType("text");

                    b.Property<string>("ArrivalTransferSeatNo")
                        .HasColumnType("text");

                    b.Property<string>("ArrivalTransferVehicle")
                        .HasColumnType("text");

                    b.Property<string>("AttendanceStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BoardType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FlightCity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly?>("HotelCheckInDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("HotelCheckOutDate")
                        .HasColumnType("date");

                    b.Property<string>("InsuranceCompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly?>("InsuranceEndDate")
                        .HasColumnType("date");

                    b.Property<string>("InsurancePolicyNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly?>("InsuranceStartDate")
                        .HasColumnType("date");

                    b.Property<string>("PersonNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ReturnAirline")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ReturnArrivalAirport")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<TimeOnly?>("ReturnArrivalTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("ReturnBaggageAllowance")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ReturnBaggagePieces")
                        .HasColumnType("integer");

                    b.Property<int?>("ReturnBaggageTotalKg")
                        .HasColumnType("integer");

                    b.Property<string>("ReturnCabinBaggage")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ReturnDepartureAirport")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<TimeOnly?>("ReturnDepartureTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("ReturnFlightCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly?>("ReturnFlightDate")
                        .HasColumnType("date");

                    b.Property<string>("ReturnPnr")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ReturnTicketNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ReturnTransferCompartmentNo")
                        .HasColumnType("text");

                    b.Property<string>("ReturnTransferDriverInfo")
                        .HasColumnType("text");

                    b.Property<string>("ReturnTransferDropoffPlace")
                        .HasColumnType("text");

                    b.Property<string>("ReturnTransferNote")
                        .HasColumnType("text");

                    b.Property<string>("ReturnTransferPickupPlace")
                        .HasColumnType("text");

                    b.Property<TimeOnly?>("ReturnTransferPickupTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("ReturnTransferPlate")
                        .HasColumnType("text");

                    b.Property<string>("ReturnTransferSeatNo")
                        .HasColumnType("text");

                    b.Property<string>("ReturnTransferVehicle")
                        .HasColumnType("text");

                    b.Property<string>("RoomNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RoomType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TicketNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ParticipantId");

                    b.HasIndex("AccommodationDocTabId");

                    b.ToTable("participant_details", null, t =>
                        {
                            t.HasCheckConstraint("CK_participant_details_arrival_baggage_pieces", "\"ArrivalBaggagePieces\" IS NULL OR \"ArrivalBaggagePieces\" > 0");

                            t.HasCheckConstraint("CK_participant_details_arrival_baggage_total_kg", "\"ArrivalBaggageTotalKg\" IS NULL OR \"ArrivalBaggageTotalKg\" > 0");

                            t.HasCheckConstraint("CK_participant_details_hotel_dates", "\"HotelCheckOutDate\" IS NULL OR \"HotelCheckInDate\" IS NULL OR \"HotelCheckOutDate\" >= \"HotelCheckInDate\"");

                            t.HasCheckConstraint("CK_participant_details_return_baggage_pieces", "\"ReturnBaggagePieces\" IS NULL OR \"ReturnBaggagePieces\" > 0");

                            t.HasCheckConstraint("CK_participant_details_return_baggage_total_kg", "\"ReturnBaggageTotalKg\" IS NULL OR \"ReturnBaggageTotalKg\" > 0");
                        });
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.ParticipantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("CheckInCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TcNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("WillNotAttend")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("CheckInCode")
                        .IsUnique();

                    b.HasIndex("EventId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("EventId", "TcNo")
                        .IsUnique();

                    b.ToTable("participants", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.ParticipantFlightSegmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Airline")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ArrivalAirport")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly?>("ArrivalDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("ArrivalTime")
                        .HasColumnType("time without time zone");

                    b.Property<int?>("BaggagePieces")
                        .HasColumnType("integer");

                    b.Property<int?>("BaggageTotalKg")
                        .HasColumnType("integer");

                    b.Property<string>("CabinBaggage")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DepartureAirport")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly?>("DepartureDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("DepartureTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("FlightCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Pnr")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SegmentIndex")
                        .HasColumnType("integer");

                    b.Property<string>("TicketNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("ParticipantId", "Direction", "SegmentIndex")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "EventId", "ParticipantId", "Direction", "SegmentIndex");

                    b.ToTable("participant_flight_segments", null, t =>
                        {
                            t.HasCheckConstraint("CK_participant_flight_segments_baggage_pieces", "\"BaggagePieces\" IS NULL OR \"BaggagePieces\" > 0");

                            t.HasCheckConstraint("CK_participant_flight_segments_baggage_total_kg", "\"BaggageTotalKg\" IS NULL OR \"BaggageTotalKg\" > 0");

                            t.HasCheckConstraint("CK_participant_flight_segments_segment_index", "\"SegmentIndex\" >= 1");
                        });
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.ParticipantItemLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ActorRole")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EventId", "ItemId", "CreatedAt")
                        .IsDescending(false, false, false, true);

                    b.HasIndex("OrganizationId", "ItemId", "ParticipantId", "CreatedAt")
                        .IsDescending(false, false, false, true);

                    b.ToTable("participant_item_logs", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.ParticipantMealSelectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid?>("OptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("OtherText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("EventId");

                    b.HasIndex("GroupId");

                    b.HasIndex("OptionId");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("OrganizationId", "ParticipantId");

                    b.HasIndex("OrganizationId", "ActivityId", "GroupId");

                    b.HasIndex("OrganizationId", "EventId", "ActivityId");

                    b.HasIndex("OrganizationId", "ActivityId", "GroupId", "ParticipantId")
                        .IsUnique()
                        .HasDatabaseName("IX_participant_meal_selections_OrganizationId_ActivityId_Grou~1");

                    b.ToTable("participant_meal_selections", null, t =>
                        {
                            t.HasCheckConstraint("CK_participant_meal_selections_option_or_other", "\"OptionId\" IS NOT NULL OR \"OtherText\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.PortalSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("EventId", "ParticipantId");

                    b.ToTable("portal_sessions", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.ActivityMealGroupEntity", b =>
                {
                    b.HasOne("Tripflow.Api.Data.Entities.EventActivityEntity", "Activity")
                        .WithMany("MealGroups")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tripflow.Api.Data.Entities.EventEntity", "Event")
                        .WithMany("ActivityMealGroups")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tripflow.Api.Data.Entities.OrganizationEntity", "Organization")
                        .WithMany("ActivityMealGroups")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Event");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.ActivityMealOptionEntity", b =>
                {
                    b.HasOne("Tripflow.Api.Data.Entities.ActivityMealGroupEntity", "Group")
                        .WithMany("Options")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tripflow.Api.Data.Entities.OrganizationEntity", "Organization")
                        .WithMany("ActivityMealOptions")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.CheckInEntity", b =>
                {
                    b.HasOne("Tripflow.Api.Data.Entities.OrganizationEntity", "Organization")
                        .WithMany("CheckIns")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.EventAccommodationSegmentEntity", b =>
                {
                    b.HasOne("Tripflow.Api.Data.Entities.EventDocTabEntity", "DefaultAccommodationDocTab")
                        .WithMany()
                        .HasForeignKey("DefaultAccommodationDocTabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tripflow.Api.Data.Entities.EventEntity", "Event")
                        .WithMany("AccommodationSegments")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefaultAccommodationDocTab");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.EventActivityEntity", b =>
                {
                    b.HasOne("Tripflow.Api.Data.Entities.EventDayEntity", "Day")
                        .WithMany("Activities")
                        .HasForeignKey("EventDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tripflow.Api.Data.Entities.EventEntity", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tripflow.Api.Data.Entities.OrganizationEntity", "Organization")
                        .WithMany("EventActivities")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Day");

                    b.Navigation("Event");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.EventDayEntity", b =>
                {
                    b.HasOne("Tripflow.Api.Data.Entities.EventEntity", "Event")
                        .WithMany("Days")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tripflow.Api.Data.Entities.OrganizationEntity", "Organization")
                        .WithMany("EventDays")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.EventDocTabEntity", b =>
                {
                    b.HasOne("Tripflow.Api.Data.Entities.EventEntity", "Event")
                        .WithMany("DocTabs")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tripflow.Api.Data.Entities.OrganizationEntity", "Organization")
                        .WithMany("DocTabs")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.EventEntity", b =>
                {
                    b.HasOne("Tripflow.Api.Data.Entities.OrganizationEntity", "Organization")
                        .WithMany("Events")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.EventGuideEntity", b =>
                {
                    b.HasOne("Tripflow.Api.Data.Entities.EventEntity", "Event")
                        .WithMany("EventGuides")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tripflow.Api.Data.Entities.UserEntity", "GuideUser")
                        .WithMany("GuidedEvents")
                        .HasForeignKey("GuideUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("GuideUser");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.EventItemEntity", b =>
                {
                    b.HasOne("Tripflow.Api.Data.Entities.EventEntity", "Event")
                        .WithMany("Items")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tripflow.Api.Data.Entities.OrganizationEntity", "Organization")
                        .WithMany("EventItems")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.EventParticipantLogEntity", b =>
                {
                    b.HasOne("Tripflow.Api.Data.Entities.OrganizationEntity", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.EventPortalEntity", b =>
                {
                    b.HasOne("Tripflow.Api.Data.Entities.EventEntity", "Event")
                        .WithOne("Portal")
                        .HasForeignKey("Tripflow.Api.Data.Entities.EventPortalEntity", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tripflow.Api.Data.Entities.OrganizationEntity", "Organization")
                        .WithMany("Portals")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.OrganizationGuideEntity", b =>
                {
                    b.HasOne("Tripflow.Api.Data.Entities.UserEntity", "GuideUser")
                        .WithMany("OrganizationGuideMemberships")
                        .HasForeignKey("GuideUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tripflow.Api.Data.Entities.OrganizationEntity", "Organization")
                        .WithMany("OrganizationGuides")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuideUser");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.ParticipantAccommodationAssignmentEntity", b =>
                {
                    b.HasOne("Tripflow.Api.Data.Entities.EventDocTabEntity", "OverrideAccommodationDocTab")
                        .WithMany()
                        .HasForeignKey("OverrideAccommodationDocTabId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tripflow.Api.Data.Entities.ParticipantEntity", "Participant")
                        .WithMany("AccommodationAssignments")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tripflow.Api.Data.Entities.EventAccommodationSegmentEntity", "Segment")
                        .WithMany("ParticipantAssignments")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OverrideAccommodationDocTab");

                    b.Navigation("Participant");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.ParticipantActivityWillNotAttendEntity", b =>
                {
                    b.HasOne("Tripflow.Api.Data.Entities.EventActivityEntity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tripflow.Api.Data.Entities.ParticipantEntity", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.ParticipantDetailsEntity", b =>
                {
                    b.HasOne("Tripflow.Api.Data.Entities.ParticipantEntity", "Participant")
                        .WithOne("Details")
                        .HasForeignKey("Tripflow.Api.Data.Entities.ParticipantDetailsEntity", "ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.ParticipantEntity", b =>
                {
                    b.HasOne("Tripflow.Api.Data.Entities.EventEntity", "Event")
                        .WithMany("Participants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tripflow.Api.Data.Entities.OrganizationEntity", "Organization")
                        .WithMany("Participants")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.ParticipantFlightSegmentEntity", b =>
                {
                    b.HasOne("Tripflow.Api.Data.Entities.EventEntity", "Event")
                        .WithMany("ParticipantFlightSegments")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tripflow.Api.Data.Entities.OrganizationEntity", "Organization")
                        .WithMany("ParticipantFlightSegments")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tripflow.Api.Data.Entities.ParticipantEntity", "Participant")
                        .WithMany("FlightSegments")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Organization");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.ParticipantMealSelectionEntity", b =>
                {
                    b.HasOne("Tripflow.Api.Data.Entities.EventActivityEntity", "Activity")
                        .WithMany("MealSelections")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tripflow.Api.Data.Entities.EventEntity", "Event")
                        .WithMany("ParticipantMealSelections")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tripflow.Api.Data.Entities.ActivityMealGroupEntity", "Group")
                        .WithMany("Selections")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tripflow.Api.Data.Entities.ActivityMealOptionEntity", "Option")
                        .WithMany("Selections")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tripflow.Api.Data.Entities.OrganizationEntity", "Organization")
                        .WithMany("ParticipantMealSelections")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tripflow.Api.Data.Entities.ParticipantEntity", "Participant")
                        .WithMany("MealSelections")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Event");

                    b.Navigation("Group");

                    b.Navigation("Option");

                    b.Navigation("Organization");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.PortalSessionEntity", b =>
                {
                    b.HasOne("Tripflow.Api.Data.Entities.EventEntity", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tripflow.Api.Data.Entities.OrganizationEntity", "Organization")
                        .WithMany("PortalSessions")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tripflow.Api.Data.Entities.ParticipantEntity", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Organization");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.UserEntity", b =>
                {
                    b.HasOne("Tripflow.Api.Data.Entities.OrganizationEntity", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.ActivityMealGroupEntity", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("Selections");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.ActivityMealOptionEntity", b =>
                {
                    b.Navigation("Selections");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.EventAccommodationSegmentEntity", b =>
                {
                    b.Navigation("ParticipantAssignments");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.EventActivityEntity", b =>
                {
                    b.Navigation("MealGroups");

                    b.Navigation("MealSelections");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.EventDayEntity", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.EventEntity", b =>
                {
                    b.Navigation("AccommodationSegments");

                    b.Navigation("ActivityMealGroups");

                    b.Navigation("Days");

                    b.Navigation("DocTabs");

                    b.Navigation("EventGuides");

                    b.Navigation("Items");

                    b.Navigation("ParticipantFlightSegments");

                    b.Navigation("ParticipantMealSelections");

                    b.Navigation("Participants");

                    b.Navigation("Portal");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.OrganizationEntity", b =>
                {
                    b.Navigation("ActivityMealGroups");

                    b.Navigation("ActivityMealOptions");

                    b.Navigation("CheckIns");

                    b.Navigation("DocTabs");

                    b.Navigation("EventActivities");

                    b.Navigation("EventDays");

                    b.Navigation("EventItems");

                    b.Navigation("Events");

                    b.Navigation("OrganizationGuides");

                    b.Navigation("ParticipantFlightSegments");

                    b.Navigation("ParticipantMealSelections");

                    b.Navigation("Participants");

                    b.Navigation("PortalSessions");

                    b.Navigation("Portals");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.ParticipantEntity", b =>
                {
                    b.Navigation("AccommodationAssignments");

                    b.Navigation("Details");

                    b.Navigation("FlightSegments");

                    b.Navigation("MealSelections");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("GuidedEvents");

                    b.Navigation("OrganizationGuideMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
