// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tripflow.Api.Data;

#nullable disable

namespace Tripflow.Api.Data.Migrations
{
    [DbContext(typeof(TripflowDbContext))]
    partial class TripflowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tripflow.Api.Data.Entities.CheckInEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CheckedInAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("EventId", "ParticipantId")
                        .IsUnique();

                    b.ToTable("checkins", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.EventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("GuideUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("GuideUserId");

                    b.HasIndex("OrganizationId", "StartDate");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.EventPortalEntity", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PortalJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("event_portals", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.OrganizationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("RequireLast4ForPortal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("RequireLast4ForQr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.ParticipantAccessEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("participant_access", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.ParticipantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CheckInCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PortalFailedAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PortalLastFailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PortalLockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CheckInCode")
                        .IsUnique();

                    b.HasIndex("EventId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("participants", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.PortalSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("portal_sessions", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.CheckInEntity", b =>
                {
                    b.HasOne("Tripflow.Api.Data.Entities.OrganizationEntity", "Organization")
                        .WithMany("CheckIns")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.EventEntity", b =>
                {
                    b.HasOne("Tripflow.Api.Data.Entities.UserEntity", "GuideUser")
                        .WithMany("GuidedEvents")
                        .HasForeignKey("GuideUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tripflow.Api.Data.Entities.OrganizationEntity", "Organization")
                        .WithMany("Events")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuideUser");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.EventPortalEntity", b =>
                {
                    b.HasOne("Tripflow.Api.Data.Entities.EventEntity", "Event")
                        .WithOne("Portal")
                        .HasForeignKey("Tripflow.Api.Data.Entities.EventPortalEntity", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tripflow.Api.Data.Entities.OrganizationEntity", "Organization")
                        .WithMany("Portals")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.ParticipantAccessEntity", b =>
                {
                    b.HasOne("Tripflow.Api.Data.Entities.OrganizationEntity", "Organization")
                        .WithMany("ParticipantAccesses")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tripflow.Api.Data.Entities.ParticipantEntity", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.ParticipantEntity", b =>
                {
                    b.HasOne("Tripflow.Api.Data.Entities.EventEntity", "Event")
                        .WithMany("Participants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tripflow.Api.Data.Entities.OrganizationEntity", "Organization")
                        .WithMany("Participants")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.PortalSessionEntity", b =>
                {
                    b.HasOne("Tripflow.Api.Data.Entities.OrganizationEntity", "Organization")
                        .WithMany("PortalSessions")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tripflow.Api.Data.Entities.ParticipantEntity", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.UserEntity", b =>
                {
                    b.HasOne("Tripflow.Api.Data.Entities.OrganizationEntity", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.EventEntity", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("Portal");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.OrganizationEntity", b =>
                {
                    b.Navigation("CheckIns");

                    b.Navigation("Events");

                    b.Navigation("ParticipantAccesses");

                    b.Navigation("Participants");

                    b.Navigation("PortalSessions");

                    b.Navigation("Portals");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Tripflow.Api.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("GuidedEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
